settings:
  legacy:
    force: false
    interval: 100ms
schema:
- name: app
  path: .
  commands:
    install:
      status: false
      method: make build
    build:
      status: true
      method: make debug_build
    run:
      status: true
      method: ./app
# use delve
#    run:
#      status: true
#      method: /go/bin/dlv
#  args:
#    - exec
#    - ./app
#    - --headless=true
#    - --listen=:2345
#    - --api-version=2
#    - --accept-multiclient
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor