#!/usr/bin/env bash

mes=$(git log -1 HEAD --pretty=format:'%s')
if [[ "$mes" =~ ^(:[a-z0-9\+\_\-]+:|Merge) ]]; then
	exit 0
fi

echo "$mes"
echo "[WARN] Change commit message."
git rest HEAD~
echo "[WARN] Commit is reset"
exit 1
